  export const doctors = [
    {
      id: 1,
      name: 'Dr. Sarah Johnson',
      specialty: 'Cardiologist',
      experience: '15 years',
      fees: '$150',
      available: true,
    },
    {
      id: 2,
      name: 'Dr. Michael Chen',
      specialty: 'Neurologist',
      experience: '12 years',
      fees: '$180',
      available: true,
    },
    {
      id: 3,
      name: 'Dr. Emily Williams',
      specialty: 'Pediatrician',
      experience: '10 years',
      fees: '$120',
      available: false,
    },
    {
      id: 4,
      name: 'Dr. James Brown',
      specialty: 'Orthopedic',
      experience: '18 years',
      fees: '$200',
      available: true,
    },
    {
      id: 5,
      name: 'Dr. Lisa Anderson',
      specialty: 'Dermatologist',
      experience: '8 years',
      fees: '$140',
      available: true,
    },
    {
      id: 6,
      name: 'Dr. Robert Taylor',
      specialty: 'General Physician',
      experience: '20 years',
      fees: '$100',
      available: true,
    },
    {
      id: 7,
      name: 'Dr. Jennifer Martinez',
      specialty: 'Ophthalmologist',
      experience: '14 years',
      fees: '$160',
      available: true,
    },
    {
      id: 8,
      name: 'Dr. David Wilson',
      specialty: 'Gastroenterologist',
      experience: '16 years',
      fees: '$170',
      available: true,
    },
    {
      id: 9,
      name: 'Dr. Amanda Lee',
      specialty: 'Cardiologist',
      experience: '11 years',
      fees: '$155',
      available: true,
    },
    {
      id: 10,
      name: 'Dr. Christopher Davis',
      specialty: 'Neurologist',
      experience: '13 years',
      fees: '$175',
      available: false,
    },
  ]
